Task 4
chubiitsa/frontend-project-lvl3 pull request #1
Opened 2021-10-26 11:53 UTC by chubiitsa

2021-10-27 09:34 UTC, MrMeison requested changes

2021-10-27 09:34 UTC, MrMeison commented on src/index.js
> +const makeCorrectLink = (link) => `https://hexlet-allorigins.herokuapp.com/get?disableCache=true&url=${encodeURIComponent(link)}`;
Давай соберем через `new URL`

2021-10-27 09:34 UTC, MrMeison commented on src/index.js
> +const makeCorrectLink = (link) => `https://hexlet-allorigins.herokuapp.com/get?disableCache=true&url=${encodeURIComponent(link)}`;
```suggestion
const addProxy = (url) => `https://hexlet-allorigins.herokuapp.com/get?disableCache=true&url=${encodeURIComponent(link)}`;
```

2021-10-27 09:34 UTC, MrMeison commented on src/index.js
> +    postId += 1;
чтобы не привязываться к позиции лучше использовать lodash `uniqueId`

2021-10-27 09:34 UTC, MrMeison commented on src/index.js
> +  const rssPosts = rssData.querySelectorAll('item');
парсинг rss лучше вынести в отдельный модуль

2021-10-27 09:34 UTC, MrMeison commented on src/index.js
> +    feedId: 0,
для чего эта ветка состояния?

2021-10-28 08:31 UTC, chubiitsa commented on src/index.js
> +  const rssPosts = rssData.querySelectorAll('item');
это про `getPostsData` и `getFeedData`? 
или вот эта тоже должна быть вместе с ними в одном модуле?
```javascript
const parseRSS = (rssString) => parser.parseFromString(rssString, 'application/xml');
```

2021-10-28 08:34 UTC, chubiitsa commented on src/index.js
> +    feedId: 0,
В этом состоянии очищается поле формы и делается активной кнопка
это происходит тогда, когда поток и посты добавились на страницу и можно пробовать добавить еще один поток

2021-10-28 09:19 UTC, MrMeison commented on src/index.js
> +    feedId: 0,
так это состояние загрузки. Предлагаю следующий вид состояния:
```
const state = {
    feeds: [], // фиды
    posts: [], // посты
    loadingProcess: { // состояние загрузки
      status: 'idle',
      error: null,
    },
    form: { // состояние формы
      error: null,
      status: 'filling',
      valid: false,
    },
    modal: { // состояние для модального окна просмотра
      postId: null,
    },
    ui: { // чисто ui состояние, в данном случае просмотренные посты
      seenPosts: new Set(),
    },
  };

```

2021-10-28 11:44 UTC, chubiitsa commented on src/index.js
> +    feedId: 0,
ты имеешь ввиду, что были разные состояния в одном замешаны? и так не должно быть

2021-10-28 14:59 UTC, MrMeison commented on src/index.js
> +    feedId: 0,
я больше к тому, что для состояния загрузки правильнее было бы выделить отдельную ветку состояния и вместо странного цифрового идентификатора использовать декларативную строчку :)

2021-11-08 18:27 UTC, MrMeison approved these changes

2021-11-08 18:27 UTC, MrMeison commented on src/parse.js
> +  getFeedData, getPostsData, parser, parseRSS,
Достаточно одного `parse`.
Необходимо добавить обработку ошибок

2021-11-12 08:46 UTC, merged